# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Build Break Fix
email: ghoshbishakh@gmail.com
description: >
  Life is short, stop arguing about emacs vs vim!
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ghoshbishakh.github.io/blog" # the base hostname & protocol for your site
twitter_username: iambishakh
github_username:  ghoshbishakh

# Build settings
markdown: kramdown
